using System.Text.Json.Serialization;

namespace Media.Database.Models
{
    /// <summary>
    /// Request model for source machine information, used to register 
    /// a new source machine or update an existing one. All of the fields
    /// are required, and all but the operating system make up a unique key 
    /// for the source machine. The operating system is included for 
    /// informational purposes only.
    /// </summary>
    public record SourceInformationResponse
    {
        /// <summary>
        /// The unique identifier for the source machine, generated by the server.
        /// </summary>
        [property: JsonPropertyName("sourceMachineUuid")]
        public required Guid SourceMachineUuid { get; set; }

        /// <summary>
        /// The source machine name, as reported by the source machine itself. 
        /// This is not guaranteed to be unique, it may not be null or empty.
        /// </summary>
        [property: JsonPropertyName("sourceMachineName")]
        public required string SourceMachineName { get; set; } = string.Empty;

        /// <summary>
        /// The device type ID, as reported by the source machine itself. 
        /// This is not guaranteed to be unique, it may not be null or empty.
        /// </summary>
        [property: JsonPropertyName("deviceTypeId")]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public required DeviceTypes DeviceTypeId { get; set; }

        /// <summary>
        /// The email address of the user associated with the source machine. 
        /// This may not be null or empty and must be verified with a one-time
        /// password code that is sent to the email address.
        /// </summary>
        [property: JsonPropertyName("emailAddress")]
        public required string EmailAddress { get; set; } = string.Empty;

        /// <summary>
        /// The cell phone number of the user associated with the source machine.
        /// This may not be null or empty and must be verified with a one-time
        /// password code that is sent to the cell phone.
        /// </summary>
        [property: JsonPropertyName("cellPhoneNumber")]
        public required string CellPhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// The first name of the user associated with the source machine.
        /// This may not be null or empty.
        /// </summary>
        [property: JsonPropertyName("firstName")]
        public required string FirstName { get; set; } = string.Empty;

        /// <summary>
        /// The last name of the user associated with the source machine.
        /// This may not be null or empty.
        /// </summary>
        [property: JsonPropertyName("lastName")]
        public required string LastName { get; set; } = string.Empty;

        /// <summary>
        /// The operating system of the source machine.
        /// This may not be null or empty. For example, 'Android', 'iOS', 'Windows', 'Linux', etc. 
        /// This is informational only and does not affect the uniqueness of the source machine.
        /// </summary>
        [property: JsonPropertyName("operatingSystem")]
        public required string OperatingSystem { get; set; } = string.Empty;

        /// <summary>
        /// The date and time when the source machine information was inserted into the database.
        /// </summary>

        [property: JsonPropertyName("insertedOn")]
        public required DateTimeOffset InsertedOn { get; init; }

        /// <summary>
        /// Indicates whether the source machine is currently active. 
        /// This may be used to inactivate a source machine without 
        /// deleting its information from the database.
        /// </summary>

        [property: JsonPropertyName("isActive")]
        public required bool IsActive { get; init; } = false;
    }
}
